services:
  periphery:
    image: ghcr.io/moghtech/komodo-periphery:${KOMODO_IMAGETAG:-latest}
    labels:
      komodo.skip:
    restart: unless-stopped
    ports:
      - "8120:8120"
    environment:
      - PERIPHERY_PASSKEYS=$KOMODO_PASSKEY
      - PERIPHERY_SSL_ENABLED=true
      - PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - ssl-certs:/etc/komodo/ssl
      - repos:/etc/komodo/repos
      - /opt/stacks:/etc/komodo/stacks
      - /opt/stacks:/opt/stacks
    logging:
      driver: ${LOGGING_DRIVER:-local}

volumes:
  ssl-certs:
  repos:
